services:
  - type: web
    name: kairos-v2-backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
  - type: web
    name: firecrawl-api
    env: docker
    dockerfilePath: server/firecrawl/apps/api/Dockerfile
    dockerContext: server/firecrawl/apps/api
    plan: free
    envVars:
      - key: PORT
        value: 3002
    autoDeploy: true
    healthCheckPath: /v1/health
    region: oregon 